import { type NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import { createSupabaseServerClient } from '@/lib/supabase/server-client';

const SendInvoiceSchema = z.object({
  to: z.array(z.string().email()).min(1, 'At least one recipient is required'),
  subject: z.string().min(1, 'Subject is required'),
  message: z.string().optional()
});

export async function POST(
  req: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const supabase = await createSupabaseServerClient();

    // Check authentication
    const { data: { user }, error: authError } = await supabase.auth.getUser();
    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Parse and validate request body
    const body = await req.json();
    const parseResult = SendInvoiceSchema.safeParse(body);

    if (!parseResult.success) {
      return NextResponse.json(
        {
          error: 'Invalid request parameters',
          details: parseResult.error.format()
        },
        { status: 400 }
      );
    }

    const { to, subject, message } = parseResult.data;
    const invoiceId = params.id;

    // Fetch invoice
    const { data: invoice, error: fetchError } = await supabase
      .from('invoices')
      .select('*')
      .eq('id', invoiceId)
      .eq('user_id', user.id)
      .single();

    if (fetchError || !invoice) {
      return NextResponse.json(
        { error: 'Invoice not found' },
        { status: 404 }
      );
    }

    // Download PDF from storage
    const { data: pdfData, error: downloadError } = await supabase.storage
      .from('invoices')
      .download(invoice.storage_path);

    if (downloadError || !pdfData) {
      console.error('Error downloading PDF:', downloadError);
      return NextResponse.json(
        { error: 'Failed to retrieve invoice PDF' },
        { status: 500 }
      );
    }

    // Convert blob to buffer
    const pdfBuffer = Buffer.from(await pdfData.arrayBuffer());
    const pdfBase64 = pdfBuffer.toString('base64');

    // Check if SendGrid is configured
    if (!process.env.SENDGRID_API_KEY || !process.env.SENDGRID_FROM_EMAIL) {
      console.error('SendGrid not configured');
      return NextResponse.json(
        { error: 'Email service not configured. Please contact support.' },
        { status: 500 }
      );
    }

    // Send email using SendGrid
    const sgMail = require('@sendgrid/mail');
    sgMail.setApiKey(process.env.SENDGRID_API_KEY);

    const emailMessage = message || `Please find attached invoice ${invoice.invoice_number}.`;

    const mailOptions = {
      to,
      from: {
        email: process.env.SENDGRID_FROM_EMAIL,
        name: 'HeySalad Cash'
      },
      subject,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center;">
            <h1 style="color: white; margin: 0;">HeySalad Cash</h1>
            <p style="color: rgba(255,255,255,0.9); margin: 10px 0 0 0;">Invoice Payment Request</p>
          </div>
          <div style="padding: 30px; background: #f8f9fa;">
            <p style="font-size: 16px; color: #333; line-height: 1.6;">
              ${emailMessage}
            </p>
            <div style="margin: 30px 0; padding: 20px; background: white; border-radius: 8px; border-left: 4px solid #667eea;">
              <p style="margin: 0 0 10px 0; color: #666; font-size: 14px;">Invoice Details:</p>
              <p style="margin: 5px 0; color: #333;"><strong>Invoice #:</strong> ${invoice.invoice_number}</p>
              <p style="margin: 5px 0; color: #333;"><strong>Amount:</strong> ${invoice.total_amount} ${invoice.currency}</p>
              <p style="margin: 5px 0; color: #333;"><strong>Due Date:</strong> ${new Date(invoice.due_date).toLocaleDateString()}</p>
            </div>
            <p style="font-size: 14px; color: #666; line-height: 1.6;">
              The invoice is attached as a PDF. You can pay using traditional methods or via cryptocurrency (USDC) on Base, Polygon, or Arc networks. Wallet addresses and QR codes are included in the PDF.
            </p>
          </div>
          <div style="padding: 20px; text-align: center; background: #e9ecef; font-size: 12px; color: #666;">
            <p style="margin: 0;">Generated by HeySalad Cash - Web3 Payment Platform</p>
            <p style="margin: 5px 0 0 0;"><a href="https://heysalad.cash" style="color: #667eea;">heysalad.cash</a></p>
          </div>
        </div>
      `,
      text: `${emailMessage}\n\nInvoice #: ${invoice.invoice_number}\nAmount: ${invoice.total_amount} ${invoice.currency}\nDue Date: ${new Date(invoice.due_date).toLocaleDateString()}\n\nPlease see the attached PDF for payment details.`,
      attachments: [
        {
          content: pdfBase64,
          filename: `${invoice.invoice_number}.pdf`,
          type: 'application/pdf',
          disposition: 'attachment'
        }
      ]
    };

    try {
      await sgMail.send(mailOptions);
    } catch (sendError: any) {
      console.error('SendGrid error:', sendError);

      // Log failed email
      await supabase.from('invoice_emails').insert({
        invoice_id: invoiceId,
        to_email: to.join(', '),
        subject,
        body: message || '',
        send_status: 'failed',
        error_message: sendError.message || 'Unknown error'
      });

      return NextResponse.json(
        { error: 'Failed to send email', details: sendError.message },
        { status: 500 }
      );
    }

    // Log successful emails
    for (const recipient of to) {
      await supabase.from('invoice_emails').insert({
        invoice_id: invoiceId,
        to_email: recipient,
        subject,
        body: message || '',
        send_status: 'sent'
      });
    }

    // Update invoice status to 'sent'
    await supabase
      .from('invoices')
      .update({ status: 'sent' })
      .eq('id', invoiceId);

    return NextResponse.json({
      success: true,
      message: `Invoice sent to ${to.length} recipient(s)`
    });
  } catch (error) {
    console.error('Error sending invoice:', error);
    return NextResponse.json(
      {
        error: 'Internal server error',
        message: error instanceof Error ? error.message : String(error)
      },
      { status: 500 }
    );
  }
}
